### ISSUE TITLE
Opt-in into the leaderboard (riders can choose to show their name on the leaderboards)

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#268]
```[tasklist]
### Tasks
- [x] Create a new route for riders to see leaderboard
- [x] Create existing leaderboard in that view
- [x] Get rid of: topbar, download button
- [ ] Make it mobile friendly
- [x] Create a setting for optional anonymization in leaderboard
- [x] Add copy to leaderboard / control to change the setting
- [x] Highlight the current rider
```
