### ISSUE TITLE
Go from one dispatch instance to two (set up for BikeBrigade Halifax)

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#381]
This is an epic to track the work that needs to be done to be able to launch an instance of bike brigade dispatch for another community. 

- [ ] Runbooks for launching (on fly.io for now) / all auxilary services you need to set up (twilio, database, mapbox, etc)
- [ ] Sign-ups are handled via mailchimp right now - the web form creates a new mailchimp contact, which creates a user via webhook. It may be necessary to have some other 
- [ ] `LocalizedDatatime` assumes EST. this timezone should be configarable per instance
- [ ] Neighborhoods (and [soon possibly intersections](#317)) are pulled from Toronto specific open data. Find some way to get other cities data in there or do something else to solve the problem of telling riders where things are before we reveal the exact address.

**Comment by danp** [comment]
Re neighborhoods, a quick search indicates it's using some geojson data currently?

I happen to have [this](https://github.com/danp/outages-to-sqlite/tree/main/places) which I'm using to turn power outage locations into neighborhoods for HRM. So hopefully we can come up with a way to make the neighborhood geojson data switchable to use something like that!
